[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sparrc/go-ping"
  version = "v1.1.0"  

[[constraint]]
  name = "github.com/loadimpact/k6"
  version = "v0.55.0"  

